### ISSUE TITLE
Emacs hangs in `let`, `loop` form

### ISSUE THREAD

**Issue by ntalbs** [clojure-emacs/clojure-mode#331]
This happens always at the end of file. When I write

```
(let [a 10]
```

or

```
(loop [a 10]
```

then hit enter key, emacs hangs. The CPU usage of Emacs process hits 100%. This problem does not happen when I write the code in the middle of file.

This seems irrelevant to cider or nrepl.

OS: Mac OS X 10.11
Emacs version: 24.5.1
clojure-mode (version 4.2.0-snapshot)  ;; 20151001.2255

**Comment by bbatsov** [comment]
Likely a regression that was introduced with the recent indentation-logic refactorings.

**Comment by expez** [comment]
@ntalbs are you running the most recent version of clojure mode?  I believe this bug has been fixed.

**Comment by expez** [comment]
@ntalbs could you try reproducing this from `emacs -q`, with only clojure-mode loaded?

**Comment by ntalbs** [comment]
OK, I will try it. However, I'm off and can not access my laptop now, I
will be able to do it on Monday.

2015년 10월 8일 (목) 오후 4:07, Lars Andersen <notifications@github.com>님이 작성:

**Comment by ntalbs** [comment]
@expez I run `emacs -Q` and load only clojure-mode, then tried the same code as I described. The same problem still occurs.

**Comment by bbatsov** [comment]
@Malabarba Can you reproduce this?

**Comment by Malabarba** [comment]
Yes, I can. :+1: On pretty much any clj file even on Emacs 25.1.

**Comment by Malabarba** [comment]
And now I can't anymore. =P

**Comment by Malabarba** [comment]
Hah. I see it now. It only happens if the file has no final newline. =P

**Comment by ntalbs** [comment]
I updated clojure-mode and now the problem has gone.
